language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

php:
  - 5.6
  - 7

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

before_script:
  - phpenv config-rm xdebug.ini
  - composer install --no-interaction --prefer-source --quiet
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
   - vendor/bin/phpunit
   - vendor/bin/phpcs
   - vendor/bin/phpmd *.php text phpmd.xml.dist
